/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Role } from './role';


export interface UserDetailDto { 
    id?: string;
    firstName?: string | null;
    lastName?: string | null;
    email?: string | null;
    isActive?: boolean;
    permissions?: number;
    createdAtUtc?: string | null;
    updatedAtUtc?: string | null;
    roles?: Array<Role> | null;
}

