/**
 * CoreData API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SystemRole } from './systemRole';


export interface UserDetailDto { 
    id?: string;
    email?: string | null;
    isActive?: boolean;
    permissions?: number;
    createdAtUtc?: string | null;
    updatedAtUtc?: string | null;
    roles?: Array<SystemRole> | null;
}

