export * from './adminUser.service';
import { AdminUserService } from './adminUser.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './enrollments.service';
import { EnrollmentsService } from './enrollments.service';
export * from './me.service';
import { MeService } from './me.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AdminUserService, AuthService, EnrollmentsService, MeService, UserService];
